# Generated by Django 4.2.7 on 2025-08-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctoravailabilityslot',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_availability_slots', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='hospital',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='The doctor availability slot this appointment was booked in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.doctoravailabilityslot'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['hospital', 'doctor', 'start_time'], name='doctor_avai_hospita_59669e_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['hospital', 'doctor', 'status'], name='doctor_avai_hospita_e11628_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['hospital', 'start_time', 'status'], name='doctor_avai_hospita_8ad7de_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['doctor', 'start_time'], name='doctor_avai_doctor__42832c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailabilityslot',
            unique_together={('hospital', 'doctor', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'scheduled_date'], name='appointment_hospita_35b109_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'doctor', 'scheduled_date'], name='appointment_hospita_27c950_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'patient'], name='appointment_hospita_c11a0e_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital', 'status'], name='appointment_hospita_ab3622_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('hospital', 'doctor', 'scheduled_date', 'scheduled_time')},
        ),
    ]
