# Generated by Django 5.0.1 on 2025-08-18 20:07

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, help_text='Name of the hospital or clinic', max_length=200)),
                ('record_type', models.CharField(choices=[('GENERAL', 'General Record'), ('LAB_RESULT', 'Lab Result'), ('IMAGING', 'Imaging/X-Ray'), ('PRESCRIPTION', 'Prescription'), ('VACCINATION', 'Vaccination Record'), ('SURGERY', 'Surgery Report'), ('DISCHARGE', 'Discharge Summary'), ('ALLERGY', 'Allergy Record'), ('DIAGNOSIS', 'Diagnosis')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('vital_signs', models.JSONField(blank=True, default=dict)),
                ('lab_results', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_confidential', models.BooleanField(default=False)),
                ('access_restricted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'NURSE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(blank=True, help_text='Name of the hospital or clinic', max_length=200)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('XRAY', 'X-Ray'), ('MRI', 'MRI Scan'), ('CT', 'CT Scan'), ('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/')),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uploaded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL)),
                ('medical_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='medical_records.medicalrecord')),
            ],
            options={
                'db_table': 'medical_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['hospital_name', 'patient'], name='medical_rec_hospita_a571f7_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['hospital_name', 'created_at'], name='medical_rec_hospita_350bca_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalrecord',
            index=models.Index(fields=['hospital_name', 'record_type'], name='medical_rec_hospita_12a171_idx'),
        ),
        migrations.AddIndex(
            model_name='medicaldocument',
            index=models.Index(fields=['hospital_name', 'medical_record'], name='medical_doc_hospita_c55bc2_idx'),
        ),
    ]
