# Generated by Django 5.0.1 on 2025-08-18 23:27

import django.db.models.deletion
from django.db import migrations, models


def set_default_hospital_records(apps, schema_editor):
    """Set default hospital for existing medical records."""
    MedicalRecord = apps.get_model("medical_records", "MedicalRecord")
    Hospital = apps.get_model("tenants", "Hospital")

    # Get the first available hospital
    default_hospital = Hospital.objects.first()
    if default_hospital:
        MedicalRecord.objects.filter(hospital__isnull=True).update(
            hospital=default_hospital
        )


def reverse_set_default_hospital_records(apps, schema_editor):
    """Reverse operation - no need to do anything."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("medical_records", "0002_auto_20250818_2325"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        # Add hospital field as nullable first
        migrations.AddField(
            model_name="medicalrecord",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="tenants.hospital",
                help_text="Hospital this record belongs to",
            ),
        ),
        # Set default hospital for existing records
        migrations.RunPython(
            set_default_hospital_records,
            reverse_set_default_hospital_records,
        ),
        # Make hospital field non-nullable
        migrations.AlterField(
            model_name="medicalrecord",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="medical_records",
                to="tenants.hospital",
                help_text="Hospital this record belongs to",
            ),
        ),
    ]
