# Type stubs for Django ORM to fix LSP errors
from typing import Any, TYPE_CHECKING
from django.db import models

if TYPE_CHECKING:
    from .models import Treatment

class TreatmentManager(models.Manager):  # type: ignore
    def all(self) -> models.QuerySet['Treatment']: ...
    def filter(self, **kwargs: Any) -> models.QuerySet['Treatment']: ...
    def select_related(self, *fields: str) -> models.QuerySet['Treatment']: ...
    def count(self) -> int: ...
    def exists(self) -> bool: ...
    def values_list(self, *fields: str, flat: bool = False) -> models.QuerySet[Any]: ...