# Generated by Django 4.2.7 on 2025-08-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('tenants', '0001_initial'),
        ('appointments', '0002_initial'),
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('treatment_type', models.CharField(choices=[('MEDICATION', 'Medication'), ('THERAPY', 'Therapy'), ('SURGERY', 'Surgery'), ('PROCEDURE', 'Procedure'), ('REHABILITATION', 'Rehabilitation'), ('COUNSELING', 'Counseling'), ('DIET_PLAN', 'Diet Plan'), ('EXERCISE', 'Exercise Program')], max_length=20)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('PLANNED', 'Planned'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled'), ('ON_HOLD', 'On Hold')], default='PLANNED', max_length=20)),
                ('instructions', models.TextField()),
                ('frequency', models.CharField(blank=True, max_length=100)),
                ('dosage', models.CharField(blank=True, max_length=100)),
                ('duration', models.CharField(blank=True, max_length=100)),
                ('side_effects', models.TextField(blank=True)),
                ('warnings', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='appointments.appointment')),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to='tenants.hospital')),
                ('medical_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='treatments', to='medical_records.medicalrecord')),
                ('patient', models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='prescribed_treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'treatments',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('medication_name', models.CharField(max_length=255)),
                ('generic_name', models.CharField(blank=True, max_length=255)),
                ('brand_name', models.CharField(blank=True, max_length=255)),
                ('dosage', models.CharField(max_length=100)),
                ('dosage_unit', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('route', models.CharField(max_length=50)),
                ('duration_days', models.IntegerField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('quantity_prescribed', models.IntegerField()),
                ('quantity_unit', models.CharField(max_length=50)),
                ('refills_allowed', models.IntegerField(default=0)),
                ('refills_used', models.IntegerField(default=0)),
                ('instructions', models.TextField()),
                ('take_with_food', models.BooleanField(default=False)),
                ('pharmacy_name', models.CharField(blank=True, max_length=255)),
                ('pharmacy_phone', models.CharField(blank=True, max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('dispensed_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='tenants.hospital')),
                ('treatment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='treatments.treatment')),
            ],
            options={
                'db_table': 'prescriptions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['hospital', 'patient'], name='treatments_hospita_fc4e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['hospital', 'status'], name='treatments_hospita_9637c1_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['hospital', 'start_date'], name='treatments_hospita_2deee8_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'treatment'], name='prescriptio_hospita_1990a7_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'is_active'], name='prescriptio_hospita_1f090a_idx'),
        ),
    ]
