# Generated by Django 5.0.1 on 2025-08-28 17:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmailRequest',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('job_profession', models.CharField(blank=True, max_length=200)),
                ('subject', models.CharField(default='Contact Form Submission', max_length=200)),
                ('message', models.TextField(blank=True)),
                ('file_attached', models.FileField(blank=True, help_text='Optional file attachment', null=True, upload_to='email_attachments/%Y/%m/%d/')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PROCESSING', 'Processing'), ('SENT', 'Sent'), ('FAILED', 'Failed'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('celery_task_id', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Email Request',
                'verbose_name_plural': 'Email Requests',
                'db_table': 'email_requests',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='email_reque_status_b2852e_idx'), models.Index(fields=['email'], name='email_reque_email_261590_idx'), models.Index(fields=['created_at'], name='email_reque_created_e7f8d7_idx')],
            },
        ),
    ]
