# Generated by Django 4.2.7 on 2025-08-06 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=True, help_text='Email verification status'),
        ),
    ]
