# Generated by Django 5.2.4 on 2025-07-20 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0002_user'),
    ]

    operations = [
    ]
