# Generated by Django 5.0.1 on 2025-08-18 20:07

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200, unique=True)),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('hospital_type', models.CharField(choices=[('GENERAL', 'General Hospital'), ('SPECIALTY', 'Specialty Hospital'), ('CLINIC', 'Clinic'), ('MEDICAL_CENTER', 'Medical Center'), ('URGENT_CARE', 'Urgent Care'), ('REHABILITATION', 'Rehabilitation Center'), ('PSYCHIATRIC', 'Psychiatric Hospital'), ('CHILDREN', "Children's Hospital"), ('WOMEN', "Women's Hospital"), ('CANCER', 'Cancer Center')], default='GENERAL', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='United States', max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('bed_count', models.IntegerField(blank=True, null=True)),
                ('emergency_services', models.BooleanField(default=True)),
                ('trauma_center_level', models.CharField(blank=True, max_length=10)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('services', models.JSONField(blank=True, default=list)),
                ('accreditations', models.JSONField(blank=True, default=list)),
                ('license_number', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hospital',
                'verbose_name_plural': 'Hospitals',
                'db_table': 'hospitals',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='hospitals_name_9e93ed_idx'), models.Index(fields=['hospital_type'], name='hospitals_hospita_2fee4a_idx'), models.Index(fields=['city', 'state'], name='hospitals_city_3b133f_idx'), models.Index(fields=['is_active'], name='hospitals_is_acti_ff4c80_idx')],
            },
        ),
    ]
