# Generated by Django 5.0.1 on 2025-08-18 23:37

from django.db import migrations, models
import django.db.models.deletion


def set_default_hospital_prescriptions(apps, schema_editor):
    """Set default hospital for existing prescriptions."""
    Prescription = apps.get_model('treatments', 'Prescription')
    Hospital = apps.get_model('tenants', 'Hospital')
    
    # Get the first available hospital
    default_hospital = Hospital.objects.first()
    if default_hospital:
        Prescription.objects.filter(hospital__isnull=True).update(hospital=default_hospital)


def reverse_set_default_hospital_prescriptions(apps, schema_editor):
    """Reverse operation - no need to do anything."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        # Add hospital field as nullable first
        migrations.AddField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prescriptions',
                to='tenants.hospital',
                help_text='Hospital this prescription belongs to'
            ),
        ),
        
        # Set default hospital for existing records
        migrations.RunPython(
            set_default_hospital_prescriptions,
            reverse_set_default_hospital_prescriptions,
        ),
        
        # Make hospital field non-nullable
        migrations.AlterField(
            model_name='prescription',
            name='hospital',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='prescriptions',
                to='tenants.hospital',
                help_text='Hospital this prescription belongs to'
            ),
        ),
    ]
