# Generated by Django 5.0.1 on 2025-08-18 23:38

import django.db.models.deletion
from django.db import migrations, models


def set_default_hospital_treatments(apps, schema_editor):
    """Set default hospital for existing treatments."""
    Treatment = apps.get_model("treatments", "Treatment")
    Hospital = apps.get_model("tenants", "Hospital")

    # Get the first available hospital
    default_hospital = Hospital.objects.first()
    if default_hospital:
        Treatment.objects.filter(hospital__isnull=True).update(
            hospital=default_hospital
        )


def reverse_set_default_hospital_treatments(apps, schema_editor):
    """Reverse operation - no need to do anything."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("treatments", "0002_auto_20250818_2337"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        # Add hospital field as nullable first
        migrations.AddField(
            model_name="treatment",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="tenants.hospital",
                help_text="Hospital this treatment belongs to",
            ),
        ),
        # Set default hospital for existing records
        migrations.RunPython(
            set_default_hospital_treatments,
            reverse_set_default_hospital_treatments,
        ),
        # Make hospital field non-nullable
        migrations.AlterField(
            model_name="treatment",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="treatments",
                to="tenants.hospital",
                help_text="Hospital this treatment belongs to",
            ),
        ),
    ]
