# Generated by Django 5.0.1 on 2025-08-18 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_remove_appointment_appointment_hospita_d5dfb2_idx_and_more'),
        ('medical_records', '0004_remove_medicaldocument_medical_doc_hospita_c55bc2_idx_and_more'),
        ('tenants', '0001_initial'),
        ('treatments', '0003_auto_20250818_2338'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_hospita_fa6004_idx',
        ),
        migrations.RemoveIndex(
            model_name='prescription',
            name='prescriptio_hospita_d65e5c_idx',
        ),
        migrations.RemoveIndex(
            model_name='treatment',
            name='treatments_hospita_efa866_idx',
        ),
        migrations.RemoveIndex(
            model_name='treatment',
            name='treatments_hospita_1937f5_idx',
        ),
        migrations.RemoveIndex(
            model_name='treatment',
            name='treatments_hospita_101223_idx',
        ),
        migrations.RemoveField(
            model_name='prescription',
            name='hospital_name',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='hospital_name',
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'treatment'], name='prescriptio_hospita_1990a7_idx'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['hospital', 'is_active'], name='prescriptio_hospita_1f090a_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['hospital', 'patient'], name='treatments_hospita_fc4e8d_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['hospital', 'status'], name='treatments_hospita_9637c1_idx'),
        ),
        migrations.AddIndex(
            model_name='treatment',
            index=models.Index(fields=['hospital', 'start_date'], name='treatments_hospita_2deee8_idx'),
        ),
    ]
