# Generated by Django 4.2.7 on 2025-08-15 11:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorSpecialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False, help_text="Is this the doctor's primary specialization?")),
                ('certification_date', models.DateField(blank=True, null=True)),
                ('certification_number', models.CharField(blank=True, max_length=100, null=True)),
                ('institution', models.CharField(blank=True, help_text='Institution where specialization was obtained', max_length=200, null=True)),
                ('years_of_experience', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Doctor Specialty',
                'verbose_name_plural': 'Doctor Specialties',
                'ordering': ['-is_primary', 'specialty__name'],
            },
        ),
        migrations.CreateModel(
            name='Specialty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(choices=[('general_medicine', 'General Medicine'), ('pediatrics', 'Pediatrics'), ('gynecology', 'Gynecology'), ('cardiology', 'Cardiology'), ('dermatology', 'Dermatology'), ('orthopedics', 'Orthopedics'), ('psychiatry', 'Psychiatry'), ('neurology', 'Neurology'), ('ophthalmology', 'Ophthalmology'), ('ent', 'ENT (Ear, Nose, and Throat)'), ('radiology', 'Radiology'), ('anesthesiology', 'Anesthesiology'), ('surgery', 'General Surgery'), ('urology', 'Urology'), ('nephrology', 'Nephrology'), ('endocrinology', 'Endocrinology'), ('gastroenterology', 'Gastroenterology'), ('pulmonology', 'Pulmonology'), ('oncology', 'Oncology'), ('rheumatology', 'Rheumatology'), ('emergency_medicine', 'Emergency Medicine'), ('family_medicine', 'Family Medicine'), ('internal_medicine', 'Internal Medicine'), ('obstetrics', 'Obstetrics'), ('pathology', 'Pathology'), ('plastic_surgery', 'Plastic Surgery'), ('sports_medicine', 'Sports Medicine')], db_index=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('certification_required', models.BooleanField(default=True)),
                ('years_of_training', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Specialty',
                'verbose_name_plural': 'Specialties',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SpecialtyStatistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_doctors', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('appointment_requests_last_month', models.IntegerField(default=0)),
                ('average_wait_days', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('specialty', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='specialty.specialty')),
            ],
            options={
                'verbose_name': 'Specialty Statistics',
                'verbose_name_plural': 'Specialty Statistics',
            },
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['code'], name='specialty_s_code_4cc8ec_idx'),
        ),
        migrations.AddIndex(
            model_name='specialty',
            index=models.Index(fields=['is_active'], name='specialty_s_is_acti_f82e29_idx'),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'doctor'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_specialties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctorspecialty',
            name='specialty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='specialists', to='specialty.specialty'),
        ),
        migrations.AddIndex(
            model_name='doctorspecialty',
            index=models.Index(fields=['doctor', 'is_primary'], name='specialty_d_doctor__7e142a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctorspecialty',
            index=models.Index(fields=['specialty'], name='specialty_d_special_079429_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctorspecialty',
            unique_together={('doctor', 'specialty')},
        ),
    ]
