# Generated by Django 4.2.7 on 2025-08-15 09:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('subscription_plans', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('subdomain', models.CharField(db_index=True, max_length=100, unique=True)),
                ('registration_number', models.CharField(max_length=100, unique=True)),
                ('tax_id', models.CharField(blank=True, max_length=100)),
                ('hospital_type', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('fax_number', models.CharField(blank=True, max_length=20)),
                ('website', models.URLField(blank=True)),
                ('address_line1', models.CharField(max_length=255)),
                ('address_line2', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('postal_code', models.CharField(max_length=20)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='hospital_logos/')),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='hospital_covers/')),
                ('primary_color', models.CharField(default='#0066cc', max_length=7)),
                ('secondary_color', models.CharField(default='#f0f8ff', max_length=7)),
                ('bed_capacity', models.IntegerField(blank=True, null=True)),
                ('established_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('subscription_status', models.CharField(choices=[('ACTIVE', 'Active'), ('SUSPENDED', 'Suspended'), ('TRIAL', 'Trial'), ('EXPIRED', 'Expired')], default='TRIAL', max_length=20)),
                ('subscription_start_date', models.DateTimeField(blank=True, null=True)),
                ('subscription_end_date', models.DateTimeField(blank=True, null=True)),
                ('max_users', models.IntegerField(default=100)),
                ('max_doctors', models.IntegerField(default=20)),
                ('max_patients', models.IntegerField(default=1000)),
                ('max_appointments_per_month', models.IntegerField(default=500)),
                ('storage_quota_gb', models.IntegerField(default=10)),
                ('is_active', models.BooleanField(default=True)),
                ('allow_online_appointments', models.BooleanField(default=True)),
                ('allow_telemedicine', models.BooleanField(default=True)),
                ('require_email_verification', models.BooleanField(default=True)),
                ('require_phone_verification', models.BooleanField(default=False)),
                ('operating_hours', models.JSONField(blank=True, default=dict)),
                ('emergency_phone', models.CharField(blank=True, max_length=20)),
                ('emergency_email', models.EmailField(blank=True, max_length=254)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('onboarded_at', models.DateTimeField(blank=True, null=True)),
                ('total_doctors', models.IntegerField(default=0)),
                ('total_patients', models.IntegerField(default=0)),
                ('total_appointments', models.IntegerField(default=0)),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='subscription_plans.subscriptionplan')),
            ],
            options={
                'db_table': 'hospitals',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['subdomain'], name='hospitals_subdoma_ffb32b_idx'), models.Index(fields=['is_active'], name='hospitals_is_acti_ff4c80_idx'), models.Index(fields=['subscription_status'], name='hospitals_subscri_db766c_idx')],
            },
        ),
    ]
