# Generated by Django 5.0.1 on 2025-08-18 20:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cancelled_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='doctor_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='parent_appointment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='follow_ups', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(limit_choices_to={'role': 'PATIENT'}, on_delete=django.db.models.deletion.CASCADE, related_name='patient_appointments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='rescheduled_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rescheduled_to', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='doctoravailabilityslot',
            name='appointment',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='booked_slot', to='appointments.appointment'),
        ),
        migrations.AddField(
            model_name='doctoravailabilityslot',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='doctoravailabilityslot',
            name='doctor',
            field=models.ForeignKey(limit_choices_to={'role': 'DOCTOR'}, on_delete=django.db.models.deletion.CASCADE, related_name='availability_slots', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='appointment',
            name='slot',
            field=models.ForeignKey(blank=True, help_text='The doctor availability slot this appointment was booked in', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointments', to='appointments.doctoravailabilityslot'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['hospital_name', 'doctor', 'start_time'], name='doctor_avai_hospita_d9828a_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['hospital_name', 'doctor', 'status'], name='doctor_avai_hospita_bac590_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['hospital_name', 'start_time', 'status'], name='doctor_avai_hospita_85deb7_idx'),
        ),
        migrations.AddIndex(
            model_name='doctoravailabilityslot',
            index=models.Index(fields=['doctor', 'start_time'], name='doctor_avai_doctor__42832c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='doctoravailabilityslot',
            unique_together={('hospital_name', 'doctor', 'start_time', 'end_time')},
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital_name', 'scheduled_date'], name='appointment_hospita_d5dfb2_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital_name', 'doctor', 'scheduled_date'], name='appointment_hospita_5c3d85_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital_name', 'patient'], name='appointment_hospita_ef1225_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['hospital_name', 'status'], name='appointment_hospita_be7867_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='appointment',
            unique_together={('hospital_name', 'doctor', 'scheduled_date', 'scheduled_time')},
        ),
    ]
