# Generated by Django 5.0.1 on 2025-08-18 23:21

import django.db.models.deletion
from django.db import migrations, models


def set_default_hospital(apps, schema_editor):
    """Set default hospital for existing appointments."""
    Appointment = apps.get_model("appointments", "Appointment")
    Hospital = apps.get_model("tenants", "Hospital")

    # Get the first available hospital
    default_hospital = Hospital.objects.first()
    if default_hospital:
        Appointment.objects.filter(hospital__isnull=True).update(
            hospital=default_hospital
        )


def reverse_set_default_hospital(apps, schema_editor):
    """Reverse operation - no need to do anything."""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0002_initial"),
        ("tenants", "0001_initial"),
    ]

    operations = [
        # Add hospital field as nullable first
        migrations.AddField(
            model_name="appointment",
            name="hospital",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="tenants.hospital",
                help_text="Hospital this appointment belongs to",
            ),
        ),
        # Set default hospital for existing records
        migrations.RunPython(
            set_default_hospital,
            reverse_set_default_hospital,
        ),
        # Make hospital field non-nullable
        migrations.AlterField(
            model_name="appointment",
            name="hospital",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="appointments",
                to="tenants.hospital",
                help_text="Hospital this appointment belongs to",
            ),
        ),
    ]
