# Generated by Django 5.0.1 on 2025-08-18 23:38

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointments", "0004_auto_20250818_2323"),
        ("tenants", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_hospita_d5dfb2_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_hospita_5c3d85_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_hospita_ef1225_idx",
        ),
        migrations.RemoveIndex(
            model_name="appointment",
            name="appointment_hospita_be7867_idx",
        ),
        migrations.RemoveIndex(
            model_name="doctoravailabilityslot",
            name="doctor_avai_hospita_d9828a_idx",
        ),
        migrations.RemoveIndex(
            model_name="doctoravailabilityslot",
            name="doctor_avai_hospita_bac590_idx",
        ),
        migrations.RemoveIndex(
            model_name="doctoravailabilityslot",
            name="doctor_avai_hospita_85deb7_idx",
        ),
        migrations.AlterUniqueTogether(
            name="appointment",
            unique_together={
                ("hospital", "doctor", "scheduled_date", "scheduled_time")
            },
        ),
        migrations.AlterUniqueTogether(
            name="doctoravailabilityslot",
            unique_together={("hospital", "doctor", "start_time", "end_time")},
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["hospital", "scheduled_date"],
                name="appointment_hospita_35b109_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["hospital", "doctor", "scheduled_date"],
                name="appointment_hospita_27c950_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["hospital", "patient"], name="appointment_hospita_c11a0e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="appointment",
            index=models.Index(
                fields=["hospital", "status"], name="appointment_hospita_ab3622_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="doctoravailabilityslot",
            index=models.Index(
                fields=["hospital", "doctor", "start_time"],
                name="doctor_avai_hospita_59669e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doctoravailabilityslot",
            index=models.Index(
                fields=["hospital", "doctor", "status"],
                name="doctor_avai_hospita_e11628_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="doctoravailabilityslot",
            index=models.Index(
                fields=["hospital", "start_time", "status"],
                name="doctor_avai_hospita_8ad7de_idx",
            ),
        ),
        migrations.RemoveField(
            model_name="appointment",
            name="hospital_name",
        ),
        migrations.RemoveField(
            model_name="doctoravailabilityslot",
            name="hospital_name",
        ),
    ]
