# Generated by Django 4.2.7 on 2025-08-15 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        ('core', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hospital',
            field=models.ForeignKey(help_text='Every user must belong to a hospital', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='tenants.hospital'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['hospital', 'role'], name='users_hospita_31afcf_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['hospital', 'is_active'], name='users_hospita_09d03c_idx'),
        ),
    ]
