# Generated by Django 5.0.1 on 2025-09-02 00:07

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="YouCamAnalysis",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        choices=[
                            ("skin_analysis", "AI Skin Analysis"),
                            ("face_analyzer", "AI Face Analyzer"),
                            ("hair_extension", "AI Hair Extension"),
                            ("lips_analysis", "AI Lips Analysis"),
                        ],
                        help_text="Type of AI analysis to perform",
                        max_length=20,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image to be analyzed",
                        upload_to="youcam/analysis_images/",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        help_text="Current processing status",
                        max_length=20,
                    ),
                ),
                (
                    "celery_task_id",
                    models.CharField(
                        blank=True,
                        help_text="Celery task ID for tracking",
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "raw_response",
                    models.JSONField(
                        blank=True, help_text="Raw response from YouCam API", null=True
                    ),
                ),
                (
                    "analysis_results",
                    models.JSONField(
                        blank=True, help_text="Processed analysis results", null=True
                    ),
                ),
                (
                    "issues_detected",
                    models.JSONField(
                        blank=True,
                        help_text="Issues detected in the analysis",
                        null=True,
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(
                        blank=True,
                        help_text="Recommendations based on analysis",
                        null=True,
                    ),
                ),
                (
                    "error_message",
                    models.TextField(
                        blank=True,
                        help_text="Error message if analysis failed",
                        null=True,
                    ),
                ),
                (
                    "retry_count",
                    models.PositiveIntegerField(
                        default=0, help_text="Number of retry attempts"
                    ),
                ),
                (
                    "max_retries",
                    models.PositiveIntegerField(
                        default=3, help_text="Maximum number of retry attempts"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "YouCam Analysis",
                "verbose_name_plural": "YouCam Analyses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="AnalysisHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("viewed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "feedback_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)],
                        help_text="User rating from 1-5",
                        null=True,
                    ),
                ),
                (
                    "feedback_comment",
                    models.TextField(
                        blank=True, help_text="User feedback comment", null=True
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="youcam.youcamanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Analysis History",
                "verbose_name_plural": "Analysis Histories",
                "ordering": ["-viewed_at"],
            },
        ),
    ]
