# Generated by Django 4.2.7 on 2025-08-08 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import medical_records.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the medical record')),
                ('diagnosis', models.TextField(help_text='Medical diagnosis description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(help_text='Patient who owns this medical record', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload medical record file (PDF, Image, etc.)', upload_to=medical_records.models.medical_record_upload_path)),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(help_text='Medical record this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Medical Record File',
                'verbose_name_plural': 'Medical Record Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
