# Generated by Django 4.2.7 on 2025-08-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now, help_text='Date of the medical record')),
                ('diagnosis', models.TextField(help_text='Medical diagnosis description')),
                ('type', models.CharField(default='Consultation', help_text='Type of medical record (e.g., Consultation, Lab Results, Prescription, X-Ray, Follow-up)', max_length=50)),
                ('status', models.CharField(choices=[('completed', 'Completed'), ('reviewed', 'Reviewed'), ('active', 'Active'), ('scheduled', 'Scheduled')], default='completed', help_text='Status of the medical record', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(blank=True, help_text='Doctor who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='doctor_records', to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(help_text='Patient who owns this medical record', on_delete=django.db.models.deletion.CASCADE, related_name='medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
