# Generated by Django 4.2.7 on 2025-08-08 07:33

from django.db import migrations, models
import django.db.models.deletion
import medical_records.models


class Migration(migrations.Migration):

    dependencies = [
        ('medical_records', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medicalrecord',
            name='doctor',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='status',
        ),
        migrations.RemoveField(
            model_name='medicalrecord',
            name='type',
        ),
        migrations.CreateModel(
            name='MedicalRecordFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(help_text='Upload medical record file (PDF, Image, etc.)', upload_to=medical_records.models.medical_record_upload_path)),
                ('file_name', models.CharField(help_text='Original file name', max_length=255)),
                ('file_size', models.PositiveIntegerField(help_text='File size in bytes')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('medical_record', models.ForeignKey(help_text='Medical record this file belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='files', to='medical_records.medicalrecord')),
            ],
            options={
                'verbose_name': 'Medical Record File',
                'verbose_name_plural': 'Medical Record Files',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
