# Generated by Django 5.0.1 on 2025-08-18 20:07

import uuid

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SubscriptionPlan",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("slug", models.SlugField(max_length=100, unique=True)),
                (
                    "plan_type",
                    models.CharField(
                        choices=[
                            ("FREE", "Free"),
                            ("BASIC", "Basic"),
                            ("PROFESSIONAL", "Professional"),
                            ("ENTERPRISE", "Enterprise"),
                            ("CUSTOM", "Custom"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("currency", models.CharField(default="USD", max_length=3)),
                (
                    "billing_cycle",
                    models.CharField(
                        choices=[
                            ("MONTHLY", "Monthly"),
                            ("QUARTERLY", "Quarterly"),
                            ("SEMI_ANNUAL", "Semi-Annual"),
                            ("ANNUAL", "Annual"),
                            ("ONE_TIME", "One-Time"),
                        ],
                        default="MONTHLY",
                        max_length=20,
                    ),
                ),
                ("trial_days", models.IntegerField(default=14)),
                ("max_users", models.IntegerField()),
                ("max_doctors", models.IntegerField()),
                ("max_patients", models.IntegerField()),
                ("max_appointments_per_month", models.IntegerField()),
                ("storage_gb", models.IntegerField()),
                ("has_telemedicine", models.BooleanField(default=True)),
                ("has_analytics", models.BooleanField(default=True)),
                ("has_api_access", models.BooleanField(default=False)),
                ("has_custom_branding", models.BooleanField(default=False)),
                ("has_priority_support", models.BooleanField(default=False)),
                ("has_data_export", models.BooleanField(default=True)),
                ("has_multi_location", models.BooleanField(default=False)),
                ("has_advanced_reporting", models.BooleanField(default=False)),
                ("features", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("is_featured", models.BooleanField(default=False)),
                ("display_order", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
            ],
            options={
                "db_table": "subscription_plans",
                "ordering": ["display_order", "price"],
                "indexes": [
                    models.Index(fields=["slug"], name="subscriptio_slug_c8f940_idx"),
                    models.Index(
                        fields=["is_active"], name="subscriptio_is_acti_4d4352_idx"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "hospital_name",
                    models.CharField(
                        help_text="Name of the hospital or clinic", max_length=200
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("TRIAL", "Trial"),
                            ("ACTIVE", "Active"),
                            ("PAST_DUE", "Past Due"),
                            ("CANCELLED", "Cancelled"),
                            ("EXPIRED", "Expired"),
                            ("SUSPENDED", "Suspended"),
                        ],
                        default="TRIAL",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateTimeField()),
                ("end_date", models.DateTimeField()),
                ("trial_end_date", models.DateTimeField(blank=True, null=True)),
                ("cancelled_at", models.DateTimeField(blank=True, null=True)),
                ("current_period_start", models.DateTimeField()),
                ("current_period_end", models.DateTimeField()),
                ("next_billing_date", models.DateTimeField(blank=True, null=True)),
                ("payment_method", models.CharField(blank=True, max_length=50)),
                ("last_payment_date", models.DateTimeField(blank=True, null=True)),
                (
                    "last_payment_amount",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                ("current_users", models.IntegerField(default=0)),
                ("current_doctors", models.IntegerField(default=0)),
                ("current_patients", models.IntegerField(default=0)),
                ("current_appointments_this_month", models.IntegerField(default=0)),
                (
                    "current_storage_gb",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("auto_renew", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                (
                    "plan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="subscriptions",
                        to="subscription_plans.subscriptionplan",
                    ),
                ),
            ],
            options={
                "db_table": "subscriptions",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["hospital_name"], name="subscriptio_hospita_4f671f_idx"
                    ),
                    models.Index(
                        fields=["status"], name="subscriptio_status_572d44_idx"
                    ),
                    models.Index(
                        fields=["end_date"], name="subscriptio_end_dat_763002_idx"
                    ),
                ],
            },
        ),
    ]
