# Generated by Django 5.0.1 on 2025-08-18 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscription_plans', '0002_auto_20250818_2336'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='subscription',
            name='subscriptio_hospita_4f671f_idx',
        ),
        migrations.RemoveField(
            model_name='subscription',
            name='hospital_name',
        ),
        migrations.AddIndex(
            model_name='subscription',
            index=models.Index(fields=['hospital'], name='subscriptio_hospita_813e31_idx'),
        ),
    ]
