# Generated by Django 4.2.7 on 2025-07-22 23:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('specialty', models.CharField(max_length=100)),
                ('experience', models.IntegerField()),
                ('education', models.TextField()),
                ('photo', models.TextField()),
                ('bio', models.TextField()),
                ('description', models.TextField(blank=True, help_text='Short hover description for HeyGen', null=True)),
                ('avatar_id', models.CharField(blank=True, help_text='HeyGen avatar ID', max_length=255, null=True)),
                ('available', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='FaceAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('patient_job', models.CharField(max_length=100)),
                ('analysis_result', models.JSONField()),
                ('pdf_path', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='HairAnalysisReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('hair_type', models.CharField(max_length=100)),
                ('hair_condition', models.CharField(max_length=100)),
                ('scalp_health', models.CharField(max_length=100)),
                ('recommendations', models.JSONField()),
                ('confidence', models.IntegerField(help_text='Confidence score 0-100')),
                ('analysis_result', models.JSONField(help_text='Full YCE response')),
                ('image_hash', models.CharField(help_text='Hash of image for privacy', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FaceRecognitionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('face_id', models.CharField(max_length=255)),
                ('confidence', models.IntegerField(help_text='Confidence score 0-100')),
                ('detected_language', models.CharField(blank=True, max_length=10, null=True)),
                ('image_hash', models.CharField(help_text='Hash of image for privacy', max_length=255)),
                ('recognition_status', models.CharField(choices=[('recognized', 'Recognized'), ('new_face', 'New Face'), ('failed', 'Failed')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('response', models.TextField()),
                ('avatar_response', models.JSONField(blank=True, null=True)),
                ('language', models.CharField(default='en', max_length=10)),
                ('speaker_type', models.CharField(choices=[('nurse', 'Nurse'), ('doctor', 'Doctor')], default='nurse', max_length=20)),
                ('face_recognition_data', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.doctor')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(max_length=100)),
                ('patient_email', models.EmailField(max_length=254)),
                ('patient_phone', models.CharField(max_length=20)),
                ('appointment_date', models.DateTimeField()),
                ('appointment_time', models.CharField(max_length=20)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.doctor')),
            ],
        ),
    ]
