# Generated by Django 4.2.7 on 2025-08-15 09:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appointments', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicalDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('document_type', models.CharField(choices=[('PDF', 'PDF Document'), ('IMAGE', 'Image'), ('XRAY', 'X-Ray'), ('MRI', 'MRI Scan'), ('CT', 'CT Scan'), ('LAB_REPORT', 'Lab Report'), ('PRESCRIPTION', 'Prescription'), ('OTHER', 'Other')], max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('file', models.FileField(upload_to='medical_documents/%Y/%m/')),
                ('file_size', models.IntegerField()),
                ('file_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'medical_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('GENERAL', 'General Record'), ('LAB_RESULT', 'Lab Result'), ('IMAGING', 'Imaging/X-Ray'), ('PRESCRIPTION', 'Prescription'), ('VACCINATION', 'Vaccination Record'), ('SURGERY', 'Surgery Report'), ('DISCHARGE', 'Discharge Summary'), ('ALLERGY', 'Allergy Record'), ('DIAGNOSIS', 'Diagnosis')], default='GENERAL', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('diagnosis', models.TextField(blank=True)),
                ('symptoms', models.TextField(blank=True)),
                ('vital_signs', models.JSONField(blank=True, default=dict)),
                ('lab_results', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_confidential', models.BooleanField(default=False)),
                ('access_restricted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('appointment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='medical_records', to='appointments.appointment')),
                ('created_by', models.ForeignKey(limit_choices_to={'role__in': ['DOCTOR', 'NURSE']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_medical_records', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'medical_records',
                'ordering': ['-created_at'],
            },
        ),
    ]
