# Generated by Django 4.2.7 on 2025-07-25 01:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Hospital or clinic name', max_length=100)),
                ('schema_name', models.CharField(help_text='Database schema identifier', max_length=63, unique=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('logo_url', models.URLField(blank=True, help_text="URL to tenant's logo image", null=True)),
                ('primary_color', models.CharField(default='#2563eb', help_text='Primary brand color (hex format)', max_length=7)),
                ('secondary_color', models.CharField(default='#64748b', help_text='Secondary brand color (hex format)', max_length=7)),
                ('accent_color', models.CharField(default='#06b6d4', help_text='Accent color for highlights', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', help_text='Background color', max_length=7)),
                ('text_color', models.CharField(default='#1e293b', help_text='Primary text color', max_length=7)),
                ('custom_css', models.TextField(blank=True, help_text='Custom CSS for advanced styling', null=True)),
                ('favicon_url', models.URLField(blank=True, help_text='URL to custom favicon', null=True)),
                ('font_family', models.CharField(default='Inter, system-ui, sans-serif', help_text='Custom font family', max_length=100)),
                ('sidebar_style', models.CharField(choices=[('light', 'Light Sidebar'), ('dark', 'Dark Sidebar'), ('branded', 'Branded Sidebar')], default='light', max_length=20)),
            ],
            options={
                'verbose_name': 'Medical Tenant',
                'verbose_name_plural': 'Medical Tenants',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TenantBrandingPreset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Preset name (e.g., Medical Blue, Healthcare Green)', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Description of this branding preset')),
                ('primary_color', models.CharField(help_text='Primary brand color', max_length=7)),
                ('secondary_color', models.CharField(help_text='Secondary brand color', max_length=7)),
                ('accent_color', models.CharField(help_text='Accent color', max_length=7)),
                ('background_color', models.CharField(default='#ffffff', max_length=7)),
                ('text_color', models.CharField(default='#1e293b', max_length=7)),
                ('font_family', models.CharField(default='Inter, system-ui, sans-serif', max_length=100)),
                ('sidebar_style', models.CharField(default='light', max_length=20)),
                ('preset_css', models.TextField(blank=True, help_text='CSS template for this preset')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Branding Preset',
                'verbose_name_plural': 'Branding Presets',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('domain', models.CharField(help_text='Domain name (e.g., clinic.example.com)', max_length=253, unique=True)),
                ('is_primary', models.BooleanField(default=False, help_text='Primary domain for this tenant')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='simple_tenant.tenant')),
            ],
            options={
                'verbose_name': 'Tenant Domain',
                'verbose_name_plural': 'Tenant Domains',
                'ordering': ['domain'],
            },
        ),
    ]
