# Generated by Django 4.2.7 on 2025-07-22 23:19

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Treatment name', max_length=200)),
                ('description', ckeditor.fields.RichTextField(help_text='Detailed treatment description')),
                ('cost', models.DecimalField(decimal_places=2, help_text='Treatment cost in USD', max_digits=10)),
                ('duration_minutes', models.PositiveIntegerField(help_text='Duration in minutes')),
                ('is_active', models.BooleanField(default=True, help_text='Is this treatment available?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Medical Treatment',
                'verbose_name_plural': 'Medical Treatments',
                'ordering': ['name'],
            },
        ),
    ]
